### ISSUE TITLE
Parity and flow control

### ISSUE THREAD

**Issue by baileyds** [beagleterm/beagle-term#44]
I'd love the ability to modify these settings..had to turn them to off for a connection last night and had to abandon my Chromebook to get it working. Great product!

**Comment by RandomlyKnighted** [comment]
I just recently came across this project and got really excited when I realized this would allow me to communicate with various devices via a Chromebook. I'm going to check out the project more and see if I can add more features to it. I'm going to try and get this feature done first. So far I've looked over Google's documentation and here's some settings that we could add. All have been available since Chrome 33. The values you see are the default values sent if not changed, which at this time are sent every time since we can only change the baud rate (bit rate).

| Name | Default Value |
| ------------- | ------------- |
| Data Bits  | 8 |
| Parity Bit  | No  |
| Stop Bit  | 1  |
| Flow Control | false |

As I said before all of these values can be altered. In case someone else picks this up and can work on it before me here's more info from Google's documentation. I've included the name that must be used in the code , a generic description so you know what it is, and the possible values that can be used.

| Name | Description | Possible Values |
| ------------- | ------------- | ------------- |
| DataBits | Data Bits  | "seven", or "eight" |
| ParityBit | Parity Bit  | "no", "odd", or "even"  |
| StopBits | Stop Bit  | "one", or "two"  |
| ctsFlowControl | Flow Control **(Optional)** | true or false |

**Comment by sunglim** [comment]
Hi @RandomlyKnighted,
Thank you for your interest. 

As you told, We can connect with explicitly setting more values as described in [chrome.serial API](https://developer.chrome.com/apps/serial)

But I'm not sure if people really want this feature. When I was in embedded device company, I rarely modified 'Data bits', 'Parity Bits', 'Stop Bit' and 'Flow Control'.

---

To config connection property, you can see [here](https://github.com/beagleterm/beagle-term/blob/master/app/main.js#L96)

It would be good if we have nice framework to draw UI, but it's still good to just simply adding more controls on main menu.

Thanks again for your interest. I would happy to accept your PR.

**Comment by RandomlyKnighted** [comment]
You're right it's rare that you need to change any of these values. However, I have had to do it with connecting to a switch. At the time I was using Putty, and I had no problem changing the setting. However, now I'm trying to see if I can switch to a Chromebook and configure switches from that. That's why I decided to start with this issue.

**Comment by RandomlyKnighted** [comment]
I've started working on this feature. I've got the UI done just gotta fix a couple things in the code.

**Comment by sunglim** [comment]
Thanks in advance!
